### PR TITLE
Deprecation fix and keymap

### PR DESCRIPTION
**Pull request by filipesilva**

### CODE REVIEW

**Comment by masnun** [comment]
Thanks, merged!

**Comment by filipesilva** [comment]
Thank you for making the package in the first place :p

**Comment by masnun** [comment]
:)

**Comment by filipesilva** [comment]
I can't seem to install it still, I think it's because it needs a new release for apm to find it. This is what I get:

```
PS C:\Users\Filipe> apm install devdocs
Installing devdocs to C:\Users\Filipe\.atom\packages failed
No available version compatible with the installed Atom version: 1.0.0
```

**Comment by filipesilva** [comment]
@masnun , can you create a new release here on github? I cannot do a PR for it, and atom will not recognize the package without it.

**Comment by masnun** [comment]
Sure

**Comment by filipesilva** [comment]
It works again on atom! thank you :D

**Comment by masnun** [comment]
I am sorry that I couldn't actively maintain it. And thanks for the awesome
PR :)

On Fri, Jul 10, 2015 at 9:39 PM, Filipe Silva <notifications@github.com>
wrote:

> It works again on atom! thank you :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masnun/atom-devdocs/pull/9#issuecomment-120438565>.
>



-- 
Abu Ashraf Masnun | +8801711960803 | http://masnun.me

**Comment by filipesilva** [comment]
Minor details, what matters is that it's up and running again!

**Pull request merged**
